### ISSUE TITLE
cannot import. Python 3.5.6 / 3.6.6 - Cuda 10.0 - Ubuntu 18.04 - 'libgdf.so' has no function, constant or global variable named 'gdf_left_join_generic'

### ISSUE THREAD

**Issue by jontis** [rapidsai/pygdf#282]
Bug:

python:
import pygdf
crashes with error 'libgdf.so' has no function, constant or global variable named 'gdf_left_join_generic'
Python 3.5.6 / 3.6.6
Cuda 10.0 
Ubuntu 18.04
libgdf                    0.1.0a3            cuda_9.0_452    gpuopenanalytics/label/dev
libgdf_cffi               0.1.0a3                py36_452    gpuopenanalytics/label/dev

Full error message:
$ python
Python 3.6.6 |Anaconda custom (64-bit)| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygdf
Traceback (most recent call last):
  File "/home/jonathan/anaconda3/lib/python3.6/site-packages/libgdf_cffi/wrapper.py", line 15, in __getattr__
    return self._cached[name]
KeyError: 'gdf_left_join_generic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonathan/anaconda3/lib/python3.6/site-packages/pygdf/__init__.py", line 1, in <module>
    from .dataframe import DataFrame
  File "/home/jonathan/anaconda3/lib/python3.6/site-packages/pygdf/dataframe.py", line 11, in <module>
    from . import cudautils, formatting, queryutils, _gdf
  File "/home/jonathan/anaconda3/lib/python3.6/site-packages/pygdf/_gdf.py", line 133, in <module>
    'left': libgdf.gdf_left_join_generic,
  File "/home/jonathan/anaconda3/lib/python3.6/site-packages/libgdf_cffi/wrapper.py", line 17, in __getattr__
    fn = getattr(self._api, name)
AttributeError: cffi library 'libgdf.so' has no function, constant or global variable named 'gdf_left_join_generic'

**Comment by jontis** [comment]
People have asked how this was solved. I created the problem myself as I did not install and update all libs at the same time. Updating everything to have the same pygdf version as libgdf removed this problem (remeber to have the gpuopenanalytics/label/dev channel open for conda). However, I still don't get the system to function. Some other issue linger, that I have made a separate issue about. Project still seem a little beta, but keep up the good work. This will be a great asset when it works reliably.

**Comment by patrickbiltgen** [comment]
Similar problem and I also created a separate issue. Very excited about this project, but I can't get the simple groupby example on github to work without crashing the Jupyter kernel. Perhaps there's something with the cudatoolkit version, pygdf, and libgdf versions all needing to be synchronized...

**Comment by jontis** [comment]
I expect CUDA version to be ok, as it is a mature project, but all RAPIDS components are probably changing rapidly, pun intended, as it is a very new project. They need to be kept in sync.
