### ISSUE TITLE
libgdf_cffi.wrapper.GDFError: CUDA ERROR. cudaSuccess: no error

### ISSUE THREAD

**Issue by mbalatsko** [rapidsai/pygdf#287]
```python
def np2pygdf(df):
    # convert numpy array to pygdf dataframe
    pdf = pygdf.DataFrame()
    for c in range(df.shape[1]):
        pdf[c] = np.ascontiguousarray(df[:,c])
    return pdf
```
Stacktrace:
```
ERROR: CUDA Runtime call cudaGetLastError() in line 153 of file /home/travis/miniconda3/conda-bld/libgdf_1538776514185/work/src/validops.cu failed with no kernel image is available for execution on the device (48).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/dataframe.py", line 98, in __init__
    self.add_column(k, series, forceindex=index is not None)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/dataframe.py", line 433, in add_column
    series = self._prepare_series_for_add(data, forceindex=forceindex)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/dataframe.py", line 406, in _prepare_series_for_add
    self._sanitize_columns(col)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/dataframe.py", line 365, in _sanitize_columns
    series = Series(col)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/series.py", line 72, in __init__
    data = columnops.as_column(data)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/columnops.py", line 156, in as_column
    data = as_column(cuda.to_device(arbitrary))
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/columnops.py", line 150, in as_column
    data = data.set_mask(mask)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/column.py", line 217, in set_mask
    return self.replace(mask=mask, null_count=null_count)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/column.py", line 323, in replace
    return type(self)(**params)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/numerical.py", line 63, in __init__
    super(NumericalColumn, self).__init__(**kwargs)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/columnops.py", line 32, in __init__
    super(TypedColumnBase, self).__init__(**kwargs)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/column.py", line 111, in __init__
    size=len(self))
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/pygdf/_gdf.py", line 544, in count_nonzero_mask
    libgdf.gdf_count_nonzero_mask(mask_ptr, size, nnz)
  File "/root/anaconda3/envs/pygdf_dev/lib/python3.5/site-packages/libgdf_cffi/wrapper.py", line 27, in wrap
    raise GDFError(errname, msg)
libgdf_cffi.wrapper.GDFError: CUDA ERROR. cudaSuccess: no error
```
Linux: docker nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04
GPU: Geforce 860M
Arrow: 0.10.0
numpy pandas from pygdf repo

**Comment by Gittry** [comment]
confirm it through both given conda installation and docker installation

**Comment by Gittry** [comment]
Confirm it via both conda and docker installation.

**Comment by Gittry** [comment]
Confirm it via both conda and docker installation.

**Comment by kkraus14** [comment]
@mbalatsko @Gittry Unfortunately, we are only supporting Pascal and newer architecture and I believe this bug stems from the GPU you're using being unsupported.

**Comment by kkraus14** [comment]
Closing as unsupported GPU architecture.
